// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the 
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the fibonacci sequence whose values do not 
// exceed four million, find the sum of the even-valued terms.

function question2() {
   "use strict";
   var input2 = Number(document.getElementById("input2").value);

   var fibSeqArray = makeFibSeqLessThan(input2);
   var evenFibSeqArray = makeEvenFibSeqArray(fibSeqArray);

   var output2a = document.getElementById("output2a");
   var output2b = document.getElementById("output2b");
   var output2c = document.getElementById("output2c");

   if (isPositiveInteger(input2)) {
      output2a.innerHTML = "All Fibonacci numbers less than " + input2 + 
         ":<br>" + array2String(fibSeqArray);
      output2b.innerHTML = "All even Fibonacci numbers less than " + 
         input2 + ":<br>" + array2String(evenFibSeqArray);
      output2c.innerHTML = "The sum of all even Fibonacci numbers less than " + 
         input2 + ":<br>" + sumArray(evenFibSeqArray);
   } else {
      output2a.innerHTML = ""; 
      output2b.innerHTML = ""; 
      output2c.innerHTML = ""; 
   }
}

function makeFibSeqLessThan(anInteger) {
   "use strict";
   var fibSeqArray = [1, 2];
   if (anInteger === 1) {
      fibSeqArray.length = 0;
   }

   if (anInteger === 2) {
      fibSeqArray.length = 1;
   }

   if (anInteger > 2) {
      while (anInteger > makeNextFibTerm(fibSeqArray)) {
         fibSeqArray.push(makeNextFibTerm(fibSeqArray));
      }
   }
   return fibSeqArray;
}

function makeNextFibTerm(fibSeqArray) {
   "use strict";
   var nextterm = fibSeqArray[fibSeqArray.length - 2] + 
      fibSeqArray[fibSeqArray.length -1];
   return nextterm;
}

function makeEvenFibSeqArray(fibSeqArray) {
   "use strict";
   var evenFibSeqArray = [];
   for (var i = 0; i < fibSeqArray.length; i = i + 1) {
      if (isEven(fibSeqArray[i])) {
         evenFibSeqArray.push(fibSeqArray[i]);
      }
   }
   return evenFibSeqArray;
}

function isEven(aNumber) {
   "use strict";
   for (var i = 0; i < aNumber; i = i + 1) {
      if (aNumber % 2 === 0) {
         return true;
      }
   }
   return false;
}
